name: XmsCore-4.1

on: [push, pull_request]

jobs:
  flake:
    name: Flake Project for ${{ matrix.python-version }}
    runs-on: ${{ matrix.platform }}

    strategy:
      fail-fast: false
      matrix:
        platform: [linux-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
      # Checkout Sources
      - name: Checkout Source
        uses: actions/checkout@v2
      # Setup Python
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      # Install Python Dependencies
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 flake8-docstrings flake8-bugbear flake8-import-order pep8-naming
      # Flake Code
      - name: Run Flake
        run: |
          flake8 --count --statistics pretty_tables/*.py

  test:
    name: Test Project for ${{ matrix.python-version }}
    runs-on: ${{ matrix.platform }}

    strategy:
      fail-fast: false
      matrix:
        platform: [linux-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
      # Checkout Sources
      - name: Checkout Source
        uses: actions/checkout@v2
      # Setup Python
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      # Install Python Dependencies
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ."[dev]"
      - name: Run Tests
        run: |
          pytest --cov=pretty_tables --cov-branch

# I'm not sure what you would have to do here to do the deploy stuff. But i'm sure it
# is all easily done in actions.